language:
os: linux
dist: xenial
compiler: gcc
addons: 
  apt:
    packages:
      - clang-tidy
      - python3-pip
      - python3-setuptools
before_install:
  - "mkdir libcheck"
  - "wget https://github.com/libcheck/check/releases/download/0.12.0/check-0.12.0.tar.gz -O - | tar -xvz"
  - "pushd check-0.12.0; ./configure --prefix=/usr; make; sudo make install; popd"
  - "pip3 install -U -r integration/requirements.txt"

script:
  - make PLATFORM=test check
  - make PLATFORM=hosted lint
  - make PLATFORM=hosted integration
