language:
os: linux
dist: xenial
compiler: gcc
addons: 
  apt:
    packages:
      - check
before_install:
  - "git clone https://github.com/libcheck/check.git -C libcheck"
  - "cd libcheck; ./configure; make; sudo make install"

script:
  - cd src && bmake check && ./check
